package RuleLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;

public class BooleanRuleData_BehaviorDescriptor extends RuleData_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor {
  public BooleanRuleData_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "RuleLanguage.structure.BooleanRuleData";
  }
}
