package RuleLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class Condition_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public Condition_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "RuleLanguage.structure.Condition";
  }
}
