package RuleLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;

public class NumberRuleData_BehaviorDescriptor extends RuleData_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor {
  public NumberRuleData_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "RuleLanguage.structure.NumberRuleData";
  }
}
