package RuleLanguage.behavior;

/*Generated by MPS */


public class RuleDataValidDependRefrence_BehaviorDescriptor extends RuleDataRefrence_BehaviorDescriptor {
  public RuleDataValidDependRefrence_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "RuleLanguage.structure.RuleDataValidDependRefrence";
  }
}
