package RuleLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Rule_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Rule_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "RuleLanguage.structure.Rule";
  }
}
