package RuleLanguage.behavior;

/*Generated by MPS */


public class RuleDateFilterbyRefrence_BehaviorDescriptor extends RuleDataRefrence_BehaviorDescriptor {
  public RuleDateFilterbyRefrence_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "RuleLanguage.structure.RuleDateFilterbyRefrence";
  }
}
