package RuleLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class RuleDataRefrence_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public RuleDataRefrence_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "RuleLanguage.structure.RuleDataRefrence";
  }
}
