package RuleLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;

public class RuleData_Constraints extends BaseConstraintsDescriptor {
  public RuleData_Constraints() {
    super("RuleLanguage.structure.RuleData");
  }
}
